name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
  runs-on: ubuntu-latest
  env:
    PYTHONPATH: ${{ github.workspace }}
    SKIP_MLFLOW: "1"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest
    - name: Generate sample dataset
      run: |
        mkdir -p data
        python - <<'PY'
        import pandas as pd
        cols = ["Blood Status","Bravery","Intelligence","Loyalty","Ambition",
                "Dark Arts Knowledge","Quidditch Skills","Dueling Skills","Creativity","House"]
        row  = ["Half-blood",5,6,6,4,2,5,5,6,"Hufflepuff"]
        pd.DataFrame([dict(zip(cols,row))]).to_csv("data/harry_potter_1000_students.csv", index=False)
        PY
    - name: Run tests
      run: pytest -q --maxfail=1

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: julessucrot2211/mlops-hogwarts:latest

  trigger_webhook:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Trigger local deploy webhook
        run: |
          curl -sSf -X POST "${{ secrets.NGROK_URL }}/deploy" \
            -H "X-Token: ${{ secrets.WEBHOOK_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{}'
